<?php


/**
 * This class defines the structure of the 'availability' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/28/12 16:40:15
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AvailabilityTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AvailabilityTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('availability');
		$this->setPhpName('Availability');
		$this->setClassname('Availability');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('AVAILABILITY_ID', 'AvailabilityId', 'INTEGER', true, 11, null);
		$this->addColumn('DAY', 'Day', 'TINYINT', false, 1, null);
		$this->addColumn('OPENING_TIME', 'OpeningTime', 'TIME', false, null, null);
		$this->addColumn('CLOSING_TIME', 'ClosingTime', 'TIME', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('ListingToAvailability', 'ListingToAvailability', RelationMap::ONE_TO_MANY, array('availability_id' => 'availability_id', ), 'RESTRICT', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // AvailabilityTableMap
