<?php


/**
 * This class defines the structure of the 'photo' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/28/12 16:40:17
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PhotoTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PhotoTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('photo');
		$this->setPhpName('Photo');
		$this->setClassname('Photo');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(false);
		// columns
		$this->addPrimaryKey('PHOTO_ID', 'PhotoId', 'INTEGER', true, 11, null);
		$this->addColumn('CONTEXT', 'Context', 'VARCHAR', false, 45, null);
		$this->addColumn('CONTEXT_ID', 'ContextId', 'INTEGER', false, 11, null);
		$this->addColumn('TITLE', 'Title', 'VARCHAR', false, 45, null);
		$this->addColumn('CAPTION', 'Caption', 'VARCHAR', false, 45, null);
		$this->addColumn('FILENAME', 'Filename', 'VARCHAR', false, 45, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('AccountToPhoto', 'AccountToPhoto', RelationMap::ONE_TO_MANY, array('photo_id' => 'photo_id', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('ListingToPhoto', 'ListingToPhoto', RelationMap::ONE_TO_MANY, array('photo_id' => 'photo_id', ), 'RESTRICT', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // PhotoTableMap
