<?php

/**
 * Base class that represents a row from the 'photo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/28/12 16:40:17
 *
 * @package    lib.model.om
 */
abstract class BasePhoto extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PhotoPeer
	 */
	protected static $peer;

	/**
	 * The value for the photo_id field.
	 * @var        int
	 */
	protected $photo_id;

	/**
	 * The value for the context field.
	 * @var        string
	 */
	protected $context;

	/**
	 * The value for the context_id field.
	 * @var        int
	 */
	protected $context_id;

	/**
	 * The value for the title field.
	 * @var        string
	 */
	protected $title;

	/**
	 * The value for the caption field.
	 * @var        string
	 */
	protected $caption;

	/**
	 * The value for the filename field.
	 * @var        string
	 */
	protected $filename;

	/**
	 * @var        array AccountToPhoto[] Collection to store aggregation of AccountToPhoto objects.
	 */
	protected $collAccountToPhotos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAccountToPhotos.
	 */
	private $lastAccountToPhotoCriteria = null;

	/**
	 * @var        array ListingToPhoto[] Collection to store aggregation of ListingToPhoto objects.
	 */
	protected $collListingToPhotos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collListingToPhotos.
	 */
	private $lastListingToPhotoCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'PhotoPeer';

	/**
	 * Get the [photo_id] column value.
	 * 
	 * @return     int
	 */
	public function getPhotoId()
	{
		return $this->photo_id;
	}

	/**
	 * Get the [context] column value.
	 * 
	 * @return     string
	 */
	public function getContext()
	{
		return $this->context;
	}

	/**
	 * Get the [context_id] column value.
	 * 
	 * @return     int
	 */
	public function getContextId()
	{
		return $this->context_id;
	}

	/**
	 * Get the [title] column value.
	 * 
	 * @return     string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Get the [caption] column value.
	 * 
	 * @return     string
	 */
	public function getCaption()
	{
		return $this->caption;
	}

	/**
	 * Get the [filename] column value.
	 * 
	 * @return     string
	 */
	public function getFilename()
	{
		return $this->filename;
	}

	/**
	 * Set the value of [photo_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setPhotoId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->photo_id !== $v) {
			$this->photo_id = $v;
			$this->modifiedColumns[] = PhotoPeer::PHOTO_ID;
		}

		return $this;
	} // setPhotoId()

	/**
	 * Set the value of [context] column.
	 * 
	 * @param      string $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setContext($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->context !== $v) {
			$this->context = $v;
			$this->modifiedColumns[] = PhotoPeer::CONTEXT;
		}

		return $this;
	} // setContext()

	/**
	 * Set the value of [context_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setContextId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->context_id !== $v) {
			$this->context_id = $v;
			$this->modifiedColumns[] = PhotoPeer::CONTEXT_ID;
		}

		return $this;
	} // setContextId()

	/**
	 * Set the value of [title] column.
	 * 
	 * @param      string $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title !== $v) {
			$this->title = $v;
			$this->modifiedColumns[] = PhotoPeer::TITLE;
		}

		return $this;
	} // setTitle()

	/**
	 * Set the value of [caption] column.
	 * 
	 * @param      string $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setCaption($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->caption !== $v) {
			$this->caption = $v;
			$this->modifiedColumns[] = PhotoPeer::CAPTION;
		}

		return $this;
	} // setCaption()

	/**
	 * Set the value of [filename] column.
	 * 
	 * @param      string $v new value
	 * @return     Photo The current object (for fluent API support)
	 */
	public function setFilename($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->filename !== $v) {
			$this->filename = $v;
			$this->modifiedColumns[] = PhotoPeer::FILENAME;
		}

		return $this;
	} // setFilename()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->photo_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->context = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->context_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->title = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->caption = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->filename = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 6; // 6 = PhotoPeer::NUM_COLUMNS - PhotoPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Photo object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PhotoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PhotoPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collAccountToPhotos = null;
			$this->lastAccountToPhotoCriteria = null;

			$this->collListingToPhotos = null;
			$this->lastListingToPhotoCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PhotoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePhoto:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				PhotoPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePhoto:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PhotoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePhoto:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePhoto:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				PhotoPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PhotoPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += PhotoPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAccountToPhotos !== null) {
				foreach ($this->collAccountToPhotos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collListingToPhotos !== null) {
				foreach ($this->collListingToPhotos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = PhotoPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAccountToPhotos !== null) {
					foreach ($this->collAccountToPhotos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collListingToPhotos !== null) {
					foreach ($this->collListingToPhotos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PhotoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getPhotoId();
				break;
			case 1:
				return $this->getContext();
				break;
			case 2:
				return $this->getContextId();
				break;
			case 3:
				return $this->getTitle();
				break;
			case 4:
				return $this->getCaption();
				break;
			case 5:
				return $this->getFilename();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PhotoPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getPhotoId(),
			$keys[1] => $this->getContext(),
			$keys[2] => $this->getContextId(),
			$keys[3] => $this->getTitle(),
			$keys[4] => $this->getCaption(),
			$keys[5] => $this->getFilename(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PhotoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setPhotoId($value);
				break;
			case 1:
				$this->setContext($value);
				break;
			case 2:
				$this->setContextId($value);
				break;
			case 3:
				$this->setTitle($value);
				break;
			case 4:
				$this->setCaption($value);
				break;
			case 5:
				$this->setFilename($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PhotoPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setPhotoId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setContext($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setContextId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTitle($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCaption($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFilename($arr[$keys[5]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PhotoPeer::DATABASE_NAME);

		if ($this->isColumnModified(PhotoPeer::PHOTO_ID)) $criteria->add(PhotoPeer::PHOTO_ID, $this->photo_id);
		if ($this->isColumnModified(PhotoPeer::CONTEXT)) $criteria->add(PhotoPeer::CONTEXT, $this->context);
		if ($this->isColumnModified(PhotoPeer::CONTEXT_ID)) $criteria->add(PhotoPeer::CONTEXT_ID, $this->context_id);
		if ($this->isColumnModified(PhotoPeer::TITLE)) $criteria->add(PhotoPeer::TITLE, $this->title);
		if ($this->isColumnModified(PhotoPeer::CAPTION)) $criteria->add(PhotoPeer::CAPTION, $this->caption);
		if ($this->isColumnModified(PhotoPeer::FILENAME)) $criteria->add(PhotoPeer::FILENAME, $this->filename);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PhotoPeer::DATABASE_NAME);

		$criteria->add(PhotoPeer::PHOTO_ID, $this->photo_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getPhotoId();
	}

	/**
	 * Generic method to set the primary key (photo_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setPhotoId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Photo (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setPhotoId($this->photo_id);

		$copyObj->setContext($this->context);

		$copyObj->setContextId($this->context_id);

		$copyObj->setTitle($this->title);

		$copyObj->setCaption($this->caption);

		$copyObj->setFilename($this->filename);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAccountToPhotos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAccountToPhoto($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getListingToPhotos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addListingToPhoto($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Photo Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PhotoPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PhotoPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collAccountToPhotos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAccountToPhotos()
	 */
	public function clearAccountToPhotos()
	{
		$this->collAccountToPhotos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAccountToPhotos collection (array).
	 *
	 * By default this just sets the collAccountToPhotos collection to an empty array (like clearcollAccountToPhotos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAccountToPhotos()
	{
		$this->collAccountToPhotos = array();
	}

	/**
	 * Gets an array of AccountToPhoto objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Photo has previously been saved, it will retrieve
	 * related AccountToPhotos from storage. If this Photo is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array AccountToPhoto[]
	 * @throws     PropelException
	 */
	public function getAccountToPhotos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PhotoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAccountToPhotos === null) {
			if ($this->isNew()) {
			   $this->collAccountToPhotos = array();
			} else {

				$criteria->add(AccountToPhotoPeer::PHOTO_ID, $this->photo_id);

				AccountToPhotoPeer::addSelectColumns($criteria);
				$this->collAccountToPhotos = AccountToPhotoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AccountToPhotoPeer::PHOTO_ID, $this->photo_id);

				AccountToPhotoPeer::addSelectColumns($criteria);
				if (!isset($this->lastAccountToPhotoCriteria) || !$this->lastAccountToPhotoCriteria->equals($criteria)) {
					$this->collAccountToPhotos = AccountToPhotoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAccountToPhotoCriteria = $criteria;
		return $this->collAccountToPhotos;
	}

	/**
	 * Returns the number of related AccountToPhoto objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related AccountToPhoto objects.
	 * @throws     PropelException
	 */
	public function countAccountToPhotos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PhotoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAccountToPhotos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AccountToPhotoPeer::PHOTO_ID, $this->photo_id);

				$count = AccountToPhotoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AccountToPhotoPeer::PHOTO_ID, $this->photo_id);

				if (!isset($this->lastAccountToPhotoCriteria) || !$this->lastAccountToPhotoCriteria->equals($criteria)) {
					$count = AccountToPhotoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collAccountToPhotos);
				}
			} else {
				$count = count($this->collAccountToPhotos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a AccountToPhoto object to this object
	 * through the AccountToPhoto foreign key attribute.
	 *
	 * @param      AccountToPhoto $l AccountToPhoto
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAccountToPhoto(AccountToPhoto $l)
	{
		if ($this->collAccountToPhotos === null) {
			$this->initAccountToPhotos();
		}
		if (!in_array($l, $this->collAccountToPhotos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAccountToPhotos, $l);
			$l->setPhoto($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Photo is new, it will return
	 * an empty collection; or if this Photo has previously
	 * been saved, it will retrieve related AccountToPhotos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Photo.
	 */
	public function getAccountToPhotosJoinAccount($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PhotoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAccountToPhotos === null) {
			if ($this->isNew()) {
				$this->collAccountToPhotos = array();
			} else {

				$criteria->add(AccountToPhotoPeer::PHOTO_ID, $this->photo_id);

				$this->collAccountToPhotos = AccountToPhotoPeer::doSelectJoinAccount($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AccountToPhotoPeer::PHOTO_ID, $this->photo_id);

			if (!isset($this->lastAccountToPhotoCriteria) || !$this->lastAccountToPhotoCriteria->equals($criteria)) {
				$this->collAccountToPhotos = AccountToPhotoPeer::doSelectJoinAccount($criteria, $con, $join_behavior);
			}
		}
		$this->lastAccountToPhotoCriteria = $criteria;

		return $this->collAccountToPhotos;
	}

	/**
	 * Clears out the collListingToPhotos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addListingToPhotos()
	 */
	public function clearListingToPhotos()
	{
		$this->collListingToPhotos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collListingToPhotos collection (array).
	 *
	 * By default this just sets the collListingToPhotos collection to an empty array (like clearcollListingToPhotos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initListingToPhotos()
	{
		$this->collListingToPhotos = array();
	}

	/**
	 * Gets an array of ListingToPhoto objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Photo has previously been saved, it will retrieve
	 * related ListingToPhotos from storage. If this Photo is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ListingToPhoto[]
	 * @throws     PropelException
	 */
	public function getListingToPhotos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PhotoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collListingToPhotos === null) {
			if ($this->isNew()) {
			   $this->collListingToPhotos = array();
			} else {

				$criteria->add(ListingToPhotoPeer::PHOTO_ID, $this->photo_id);

				ListingToPhotoPeer::addSelectColumns($criteria);
				$this->collListingToPhotos = ListingToPhotoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ListingToPhotoPeer::PHOTO_ID, $this->photo_id);

				ListingToPhotoPeer::addSelectColumns($criteria);
				if (!isset($this->lastListingToPhotoCriteria) || !$this->lastListingToPhotoCriteria->equals($criteria)) {
					$this->collListingToPhotos = ListingToPhotoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastListingToPhotoCriteria = $criteria;
		return $this->collListingToPhotos;
	}

	/**
	 * Returns the number of related ListingToPhoto objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ListingToPhoto objects.
	 * @throws     PropelException
	 */
	public function countListingToPhotos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PhotoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collListingToPhotos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ListingToPhotoPeer::PHOTO_ID, $this->photo_id);

				$count = ListingToPhotoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ListingToPhotoPeer::PHOTO_ID, $this->photo_id);

				if (!isset($this->lastListingToPhotoCriteria) || !$this->lastListingToPhotoCriteria->equals($criteria)) {
					$count = ListingToPhotoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collListingToPhotos);
				}
			} else {
				$count = count($this->collListingToPhotos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ListingToPhoto object to this object
	 * through the ListingToPhoto foreign key attribute.
	 *
	 * @param      ListingToPhoto $l ListingToPhoto
	 * @return     void
	 * @throws     PropelException
	 */
	public function addListingToPhoto(ListingToPhoto $l)
	{
		if ($this->collListingToPhotos === null) {
			$this->initListingToPhotos();
		}
		if (!in_array($l, $this->collListingToPhotos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collListingToPhotos, $l);
			$l->setPhoto($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Photo is new, it will return
	 * an empty collection; or if this Photo has previously
	 * been saved, it will retrieve related ListingToPhotos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Photo.
	 */
	public function getListingToPhotosJoinListing($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PhotoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collListingToPhotos === null) {
			if ($this->isNew()) {
				$this->collListingToPhotos = array();
			} else {

				$criteria->add(ListingToPhotoPeer::PHOTO_ID, $this->photo_id);

				$this->collListingToPhotos = ListingToPhotoPeer::doSelectJoinListing($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(ListingToPhotoPeer::PHOTO_ID, $this->photo_id);

			if (!isset($this->lastListingToPhotoCriteria) || !$this->lastListingToPhotoCriteria->equals($criteria)) {
				$this->collListingToPhotos = ListingToPhotoPeer::doSelectJoinListing($criteria, $con, $join_behavior);
			}
		}
		$this->lastListingToPhotoCriteria = $criteria;

		return $this->collListingToPhotos;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAccountToPhotos) {
				foreach ((array) $this->collAccountToPhotos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collListingToPhotos) {
				foreach ((array) $this->collListingToPhotos as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAccountToPhotos = null;
		$this->collListingToPhotos = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BasePhoto:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BasePhoto::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BasePhoto
