# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

account-request-reset-password:
  url: /account/account-request-reset-password
  param: { module: register, action: requestResetPassword }

account-reset-password:
  url: /account/reset-password
  param: { module: register, action: resetPassword }

  
register:
  url:     /register.:sf_format
  class:   sfPropelRoute
  options: { model: Account, type: list }
  param:   { module: register, action: index, sf_format: html }
  requirements: { sf_method: get }
 
register_create:
  url:     /register.:sf_format
  class:   sfPropelRoute
  options: { model: Account, type: object }
  param:   { module: register, action: create, sf_format: html }
  requirements: { sf_method: post }
  
login:
  url:     /login.:sf_format
  param:   { module: login, action: index, sf_format: html }
  requirements: { sf_method: get }
  
activate:
  url:		/activate/verify
  param:    { module: activate, action: index, sf_format: html }
  requirements: { sf_method: get }

default:
  url:   /:module/:action/*

