<?php


/**
 * Skeleton subclass for performing query and update operations on the 'account' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/28/12 15:49:29
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AccountPeer extends BaseAccountPeer {
	
	const UNVERIFIED = 1 ;
	
	const VERIFIED = 2 ;


	public static function retrieveByEmail($email)
	{
		$criteria = new Criteria();
		$criteria->add(self::EMAIL,$email);
		$criteria->add(self::STATUS,self::VERIFIED);

		return self::doSelectOne($criteria);
	}
	
	public static function getAccount($email,$password)
	{
		$criteria = new Criteria();
		$criteria->add(self::EMAIL,$email);
		$criteria->add(self::PASSWORD,$password);
		
		return self::doSelectOne($criteria);
	}
} // AccountPeer
