<?php


/**
 * Skeleton subclass for performing query and update operations on the 'listing' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/28/12 15:49:30
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ListingPeer extends BaseListingPeer {

	public static function getUserListings($accountId)
	{
		$criteria = new Criteria();
		$criteria->add(self::ACCOUNT_ID,$accountId);
		
		return self::doSelect($criteria);
	}
	
	public static function getListingByOwner($accountId, $listingId){
		$criteria = new Criteria();
		$criteria->add(self::ACCOUNT_ID,$accountId);
		$criteria->add(self::LISTING_ID,$listingId);
		
		return self::doSelectOne($criteria);
	}
	
	public static function getAccountIdByOwner($listingId){
		$criteria = new Criteria();
		$criteria->add(self::LISTING_ID,$listingId);
		
		return self::doSelectOne($criteria);
	}
} // ListingPeer
