<?php


/**
 * Skeleton subclass for representing a row from the 'listing' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/28/12 15:49:30
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Listing extends BaseListing {

	public function getMapInfo()
	{
		$maps = $this->getMapInfos();
		
		if (!empty($maps)) {
			return $maps[0];
		}
		
		return null;
	}

} // Listing
