<?php


/**
 * Skeleton subclass for performing query and update operations on the 'map_info' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/28/12 15:49:32
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MapInfoPeer extends BaseMapInfoPeer {
	
	public static function getMapInfoOfListing($listingId){
		$criteria = new Criteria();
	//	$criteria->add(self::LISTING_ID,$listingId);  //<-real code
	// temporarily map_info_id
		$criteria->add(self::MAP_INFO_ID, $listingId);
		return self::doSelectOne($criteria);
	}
} // MapInfoPeer
