<?php


/**
 * Skeleton subclass for performing query and update operations on the 'token' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 04/28/12 15:49:32
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TokenPeer extends BaseTokenPeer {
	
	public static function getTokenVerificationCode($verificationCode)
	{
		$c = new Criteria();
		$c->add(self::TOKEN_ID, $verificationCode);
		$c->add(self::EXPIRES_AT, date('Y-m-d H:i:s'), Criteria::GREATER_EQUAL);
		return self::doSelectOne($c);
	}

} // TokenPeer
